### ISSUE TITLE
Define a meaningful behavior and life cycle options of ManagedOSImage resource

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1268] opened 2024-03-05 09:30 UTC
* Is it an editable resource?
  * add new clusters
  * setting different os image
  * etc.

**Comment by davidcassany** [comment] 2024-03-05 17:18
While testing rancher/elemental-toolkit#1990 as I needed to test more than one upgrade in sequence I took the chance to run a particular case in which a new upgrade group is created for each upgrade without deleting the previous one.

I tried to document the behavior of that particular case in detail in a comment https://github.com/rancher/elemental-toolkit/pull/1990#issuecomment-1979254792

**Comment by anmazzotti** [comment] 2024-03-06 15:49
https://github.com/rancher/elemental-operator/pull/658 makes the ManagedOSImage editable.

Now any change should lead to the triggering of a new "update".
What technically happens is that on ManagedOSImage creation, a owned Fleet Bundle will be created. 
Among some default resources, one in particular defines the Plan to execute: 
```yaml
    - content: '{"kind":"Plan","apiVersion":"upgrade.cattle.io/v1","metadata":{"name":"os-upgrader-dev-upgrade","namespace":"cattle-system","creationTimestamp":null},"spec":{"concurrency":1,"nodeSelector":{},"serviceAccountName":"os-upgrader-dev-upgrade","version":"dev-next-2","secrets":[{"name":"os-upgrader-dev-upgrade","path":"/run/data"}],"tolerations":[{"operator":"Exists"}],"cordon":true,"upgrade":{"image":"172.18.0.2:30000/elemental-os","command":["/usr/sbin/suc-upgrade"],"envs":[{"name":"FORCE","value":"false"},{"name":"UPGRADE_RECOVERY","value":"true"},{"name":"UPGRADE_RECOVERY_ONLY","value":"false"}]}},"status":{}}'
      name: Plan-cattle-system-os-upgrader-dev-upgrade-ef3a9756fa46.yaml
``` 

Updating the ManagedOSImage will lead to the update of this resource, the Bundle be reprocessed and the `system-upgrade-controller` running on the downstream cluster should apply the plan again.

Note that on the nodes we will have 1 label only and not a new one per "update":
```
plan.upgrade.cattle.io/os-upgrader-dev-upgrade: 8aa559e715bd6b1523ea12b2d586dac3478e19e52fb431cdb7e21a31
```

It is possible to verify the correct application of the latest plan:
```
kubectl -n cattle-system get plans os-upgrader-dev-upgrade -o jsonpath='{.status.latestHash}{"\n"}'
8aa559e715bd6b1523ea12b2d586dac3478e19e52fb431cdb7e21a31
```

But we do lose history on the previous plans. 
Since we do not know when a Plan is completely executed on each targeted cluster, we can't stop the user from updating the ManagedOSImage in case of (previous) Plan failures. 

It can happen that X nodes fail to upgrade for some reason, but do so "silently" because we don't report back the Plan status.
I think the simplest way to address this is to raise attention to the end users, that they **need** to monitor the downstream upgrade pods as part of the Elemental upgrade process.

I do mention the pods because I don't think this the Plan has a "Completed" status. 
Edit: Seems ["Complete" status](https://github.com/rancher/system-upgrade-controller/issues/291) was merged one week ago! Great timing!

In any case all that I just wrote could be part of the documentation.

**Comment by davidcassany** [comment] 2024-03-07 08:43
> I do mention the pods because I don't think this the Plan has a "Completed" status.
> Edit: Seems ["Complete" status](https://github.com/rancher/system-upgrade-controller/issues/291) was merged one week ago! Great timing!

Well the problem we will have here is how to control the system-upgrade-controller version we include, I think this comes as part of the provisioning, hence we might have no influence on which version of the controller are we using, more over, there could be different versions on different downstream clusters I guess...

In addition this, SUC also merged an `exclusive` flag to prevent concurrent plans that would be really helpful in our case to prevent concurrent upgrades (https://github.com/rancher/system-upgrade-controller/pull/260).

Also, I am not sure how the complete status is tracked, but what we have today is a list of the running pods in status, which could be used to track that. The real problem though is not how the plan tracks status, we already have that, the problem is how fleet tracks plans status. Fleet only tracks the ready condition of the plan... So in order to bring upgrade conditions to upstream cluster we need SUC and fleet to speak to each other. I wonder if there is a way in fleet to define which conditions to track from created resources (I could' t see it in docs and this is probably a fairly complicated or convoluted feature).

I know fleet can wait for jobs, so probably we could create a job that creates the plan and include our own criteria in that job to stop once the plan is completed. Then it would be hard to manage situations like upscaling the cluster and similar operations. Mostly because in that context I would tie the job lifecycle with the plan lifecycle... 🤔

**Comment by anmazzotti** [comment] 2024-03-08 13:01
I opened a parallel issue for the `system-upgrade-controller` alone: #1274 
I think this issue still misses a bit of documentation to be closed. 

Functionality is there, but it's maybe worth mentioning on the docs that the ManagedOSImage is editable.

**Closed as completed** 2024-03-11 13:53 UTC
