### ISSUE TITLE
Installation of Dev ISO on Operator Stable is failing

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#694] opened 2023-02-24 10:29 UTC
**What steps did you take and what happened:**
On a Rancher Manager v2.7.1 I installed Elemental Operator Stable (so v1.0.2) and I tried to deploy an Elemental Teal OS from Dev branch: it failed!

The OS cannot even be installed, I have an error in `elemental-register`:
![Screenshot from 2023-02-24 10-32-34](https://user-images.githubusercontent.com/25102165/221155433-2590feb9-427c-4cd8-9d3a-517a463868d2.png)

**What did you expect to happen:**
OS should be deployed on the node and added in the k8s cluster after the reboot.

**Anything else you would like to add:**
Easy to reproduce, not sporadic.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Dev one (v1.1.1-91.3)
- Rancher version: Stable v2.7.1
- Kubernetes version (use `kubectl version`): Not installed yet
- Cloud provider or hardware configuration: N/A

**Comment by kkaempf** [comment] 2023-02-24 11:07
Hmm, operator should always be same or newer than the node. Mixing stable operator with dev node won't work in most cases.

**Comment by kkaempf** [comment] 2023-02-24 11:08
That said, using a dev operator and a stable node image should work 🤞🏻

**Comment by davidcassany** [comment] 2023-02-24 11:19
> Hmm, operator should always be same or newer than the node. Mixing stable operator with dev node won't work in most cases.

While I agree this the desired scenario I am not sure we should enforce it. Consider that elemental-operator upgrades might have very different cadence than what is deployed on a certain specific cluster. That's why I'd enforce testing both edges (newest operator on oldest teal and vice versa) for our releases, in line with https://github.com/rancher/elemental/issues/651#issuecomment-1425447142

**Comment by kkaempf** [comment] 2023-02-24 11:37
imho we should enforce timely updates of `elemental-operator` and always assume that operator is "newer" than node-image.

**Comment by fgiudici** [comment] 2023-02-24 12:17
In this case, the issue is that the current stable release doesn't even have the "version" protocol check message. We introduced register protocol versioning (that allows us to deal with new supported messages) exactly to avoid issues with different versions 😆 
In this case it is a bit tricky as the old operator rejects version negotiation by closing the connection.
Well, it is enough to get that as a sign that the supported version is the pre-version message.
It is not hard to add, I am for taking care of this case too (PR should be small)

**Comment by fgiudici** [comment] 2023-02-27 20:19
Managing the updates to older operators required not only to fix the registration protocol, but to manage the conversion of the cloud-init serialized format (which has been changed with the kubebuilder rework).

**Comment by fgiudici** [comment] 2023-02-28 18:29
The current stable operator (1.0.x) is quite different than what we have right now (in 1.1.x  the operator has been rewritten with kubebuilder), so supporting backward compatibility would require to:
- retry the connection to the operator if the protocol negotiation fails: protocol negotiation has been introduced to allow compatibility between different versions of the operator and the register client. The 1.0.x operator misses it.
- convert the serialized cloud-config data sent from the operator to the legacy format
After discussion in the team, we decided to not merge the PR fixing this issue as the impact on code readability and complexity is too high for supporting newer elemental ISO (1.1.x) with our current stable version (1.0.x). Newer ISO should be used with newer operators.

**Closed** 2023-02-28 18:29 UTC
Labels: kind/bug, area/elemental, area/elemental-operator
