### ISSUE TITLE
Bare metal testing observation - issue with IPV6 , error during inventory .

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental#303] opened 2022-08-31 11:47 UTC
ime="2022-08-31T08:45:17Z" level=error msg="failed to update inventory labels: MachineInventory.elemental.cattle.io \"machine1\" is invalid: metadata.labels: Invalid value: \"fd00::5952:8c67:7d4d:7fb\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"

The value is valid IPV6 address , further installation get struck .

**Comment by kkaempf** [comment] 2022-08-31 12:02
Duplicate of https://github.com/rancher/elemental-operator/issues/115

As Rancher doesn't fully support IPv6 yet, we postponed this issue for now.

**Closed by kkaempf** 2022-08-31 12:02 UTC

**Comment by kkaempf** [comment] 2022-09-02 06:01
We implemented a workaround in https://github.com/rancher/elemental-operator/pull/154
