### ISSUE TITLE
ManagedOSVersionChannels Failed channel synchronization

### ISSUE THREAD

**Issue by xintena** [rancher/elemental#1499] opened 2024-07-21 12:31 UTC
racnher: v2.8.5
elemental-operator: v1.5.3
elemental: v1.3.0
elemental-channel pod is  automatically deleted
![channel](https://github.com/user-attachments/assets/5cfd9655-c555-465a-986b-1132a5b2f9c8)

`apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-21T11:47:40Z"
  name: "111"
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: ManagedOSVersionChannel
    name: "111"
    uid: b2bf46ef-bbdd-41e7-a687-ee60164d4209
  resourceVersion: "8061081"
  uid: eb4ef07b-780b-4419-bd53-0300f90007e5
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - display
    - --file
    - /data/output
    image: rancher/mirrored-elemental-operator:1.5.3
    imagePullPolicy: IfNotPresent
    name: display
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: output
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - image: registry.suse.com/rancher/elemental-channel:1.5.3
    imagePullPolicy: Always
    name: runner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: output
  nodeName: local-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: output
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-21T11:47:47Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-21T11:47:49Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-21T11:47:49Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-21T11:47:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://33855f6ca90a4ec32bf113d65bf4b3c1a769028026fb81aeebe2c271ed610c4b
    image: docker.io/rancher/mirrored-elemental-operator:1.5.3
    imageID: docker.io/rancher/mirrored-elemental-operator@sha256:393fa93a25cd313563c6db79c8ed343ff9c4b251f3d6e7513e50126e43c71402
    lastState: {}
    name: display
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://33855f6ca90a4ec32bf113d65bf4b3c1a769028026fb81aeebe2c271ed610c4b
        exitCode: 0
        finishedAt: "2024-07-21T11:47:48Z"
        reason: Completed
        startedAt: "2024-07-21T11:47:48Z"
  hostIP: 172.17.0.2
  initContainerStatuses:
  - containerID: containerd://525127d3d97219135af6e2b50bdca97de0a2bf027caaadac39fde271e270e3b7
    image: registry.suse.com/rancher/elemental-channel:1.5.3
    imageID: registry.suse.com/rancher/elemental-channel@sha256:b110130d024847e3e442626b9eeafb945e615a0a8e055da208a20304cc404868
    lastState: {}
name: runner
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://525127d3d97219135af6e2b50bdca97de0a2bf027caaadac39fde271e270e3b7
        exitCode: 0
        finishedAt: "2024-07-21T11:47:46Z"
        reason: Completed
        startedAt: "2024-07-21T11:47:46Z"
  phase: Succeeded
  podIP: 10.42.0.147
  podIPs:
  - ip: 10.42.0.147
  qosClass: BestEffort
  startTime: "2024-07-21T11:47:40Z"

`

**Comment by kkaempf** [comment] 2024-07-22 08:10
Please update `elemental-operator` to 1.5.4

**Comment by xintena** [comment] 2024-07-22 08:25
> Please update `elemental-operator` to 1.5.4
thanks for your reply and i follow you，but failed

![1](https://github.com/user-attachments/assets/a559364c-ea82-43fd-9784-6aff4cd4f1c3)
![2](https://github.com/user-attachments/assets/24d52a4c-1e87-4476-b4e8-b5f11d53e2e3)

![3](https://github.com/user-attachments/assets/e3258c5e-f99b-4bb0-94a3-04a05bc110ef)
![4](https://github.com/user-attachments/assets/20648419-4456-4365-a00f-58d07bed4093)

**Comment by fgiudici** [comment] 2024-07-26 14:23
Hi @xintena  👋🏼 
we are aware of an Elemental version 1.5.3  channel sync error that may cause an endless loop of creation/destroy of the worker pod. The issue is annoying, but it happens after a successful sync already happened, so that the related ManagedOSVersion resources (the OS images) are already populated and available.
Since the channel for 1.5.3 is never updated, this is not going to cause any critical issue btw.

Here it seems the case is different: the "OS Versions" item in the first pic shows one entry (?!). Weird, as the entries should be multiple or none, but the UI number may be not updated or one could have been added manually.
Please, check with `kubectl get managedosversions.elemental.cattle.io -n fleet-default` that multiple OS images are present to confirm this.

The 1.5.4 version fixed the channel sync issue above mentioned, moreover fixes also a bug that prevented the channel to resync automatically every hour (or according to the ManagedOSVersionChannel.spec.syncInterval value if has been changed). This is why we asked to try to update to 1.5.4.

The upgrade to 1.5.4 as performed above, while done just upgrading the chart container images values, should actually work as a regular 1.5.4 version deployment (a chart updated to 1.5.4 will be released in the marketplace in the forthcoming Rancher versions). We didn't expected any error, and this is a new issue for us.
I tried to reproduce with no luck with both a fresh installation and an upgrade from a precedent version.

In order to understand what is going on, would you mind to share the logs of the elemental-channel pod and the one of the elemental operator deployment?

`kubectl logs -n fleet-default pods/elemental-channel --all-containers`
`kubectl logs -n cattle-elemental-system deployments/elemental-operator`

Many thanks

**Comment by fgiudici** [comment] 2024-08-06 07:34
Hey @xintena , 1.5.4 has been released in Rancher 2.9.
The issues with channel sync should be solved, going to close this.
If you have still issues, please reach out and/or reopen this attaching the logs from the elemental-operator: that could give us some more insights of what is going on.

**Closed as completed by fgiudici** 2024-08-06 07:34 UTC
Labels: kind/bug
